spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/specification
    username: postgres
    password: 41l154@C
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
